# Site settings
title: Interactive Resume
description: Online resume
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sarvesh Prattipati
user_description: Data Scientist passionate about data
user_title: Data Scientist | Software Engineer
email: prattipatisarvesh@gmail.com
github_username:  SarveshP
linkedin_username:  sarveshprattipati

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
